#!/bin/bash

cd /home/mat/Documents/ProgramExperiments

read -p "what would you like to name the folder? " folder_name
mkdir $folder_name
cd $folder_name
python3 -m venv ./venv
source ./venv/bin/activate
vim main.py
